name: demoapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_html: ^0.11.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  geolocator: ^5.1.3
  rflutter_alert:
  location:
  url_launcher:
  fluttertoast:
  shared_preferences:
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/icon.png"
    

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - data_repo/starwars_data.json
    - assets/images/ScenicView2.png
    - assets/about.json
    - assets/symptoms.json
    - assets/prevention.json
    - assets/images/location.png
    - assets/images/riskfact.png
    - assets/images/symptom.png
    - assets/images/mask.png
    - assets/images/whatis.png
    - assets/images/Splashvactor.png
    - assets/images/infoform.png  
    - assets/images/NMCIcon1.png
    - assets/images/faqIcon1.png
    - assets/images/DisclaimerIcon1.png
    - assets/images/AskanexpertIcon1.png
    - assets/images/CaseofMonthIcon1.png
    - assets/images/TalktolawyerIcon1.png
    - assets/images/virus.png
    - assets/images/news.png
    - assets/images/user.png
    - assets/images/symptomes.png
    - assets/images/sheld.png
    - assets/images/crona.png
    - assets/images/news_baner.png
    - assets/images/test.png
    - assets/images/what.png
    - assets/images/prev.png
    - assets/images/sympt.png
    - assets/images/colds.png
    - assets/images/cough.png
    - assets/images/diarrhea.png
    - assets/images/fatigue.png
    - assets/images/feve.png
    - assets/images/headache.png
    - assets/images/map.png
    - assets/images/patent.png
    - assets/images/sorethrat.png
    - assets/images/travel.png
    - assets/images/short.png
    - assets/images/bhati.png
    - assets/images/bodypan.png
    - assets/images/ref1.png
    - assets/images/ref2.png
    - assets/images/ref3.png
    - assets/images/ref4.png
    - assets/images/ref5.png
    - assets/images/low.png
    - assets/images/medium.png
    - assets/images/high.png
    - assets/images/risk.png
    - assets/images/icon.png
    

    
    
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
